//! ---
//! csr: "fflags"
//! mode: "urw"
//! id: 0x001
//! tag: "fp"
//! ---
//! The fflags (Floating-Point Accrued Exceptions) register is an XLEN-bit read/write register
//! that accumulates exception flags generated by floating-point instructions.
//!
//！- Side Effects:
//!   - Write: writes will set `mstatus.fs` to dirty, even if the value is unchanged.
//! - Exceptions:
//!   - Attempt to access if `mstatus.fs` is disabled.

// - Fields: holds the lowest 5-bit value as FFLAGS.

func Read_FFLAGS() => CsrReadResult
begin
  if !isEnabled_FS() then
    return CsrReadIllegalInstruction();
  end

  return CsrReadOk([
    Zeros(27),
    FFLAGS
  ]);
end

func GetRaw_FFLAGS() => bits(XLEN)
begin
  return [Zeros(27), FFLAGS];
end

func Write_FFLAGS(value: bits(32)) => Result
begin
  if !isEnabled_FS() then
    return IllegalInstruction();
  end

  // uppper bits are ignored, required by spec
  FFLAGS = value[4:0];

  logWrite_FCSR();

  // set mstatus.fs = dirty
  makeDirty_FS();

  return Retired();
end
