#!/usr/bin/env bash

#This script is used to generate the Verilog block from T1.sv + AXI Lite Wrapper, which is required by Vivado to import as a design block
# ./gen_wrapper.sh <rtl_dir> <output_file>

set -e

RTL_DIR="$1"
OUTPUT="$2"

if [ -z "$RTL_DIR" ] || [ -z "$OUTPUT" ]; then
    echo "Usage: gen_wrapper.sh <rtl_dir> <output_file>"
    exit 1
fi

T1_SV="${RTL_DIR}/T1.sv"
if [ ! -f "$T1_SV" ]; then
    echo "ERROR: T1.sv not found at ${T1_SV}"
    exit 1
fi

#Extract AXI ID width from the highBandwidthLoadStorePort_aw_bits_id port
AXI_ID_W=$(grep 'highBandwidthLoadStorePort_aw_bits_id' "$T1_SV" | head -1 | grep -oP '\[(\d+):0\]' | grep -oP '\d+' | head -1)
AXI_ID_W=$((AXI_ID_W + 1))

#Extract highBandwidth data width
HB_DATA_W=$(grep 'highBandwidthLoadStorePort_w_bits_data' "$T1_SV" | head -1 | grep -oP '\[(\d+):0\]' | grep -oP '\d+' | head -1)
HB_DATA_W=$((HB_DATA_W + 1))

#Extract highBandwidth strb width
HB_STRB_W=$(grep 'highBandwidthLoadStorePort_w_bits_strb' "$T1_SV" | head -1 | grep -oP '\[(\d+):0\]' | grep -oP '\d+' | head -1)
HB_STRB_W=$((HB_STRB_W + 1))

#Indexed port is always 32-bit data, 4-bit strb
IDX_DATA_W=32
IDX_STRB_W=4

echo "Generating wrapper: AXI_ID_W=${AXI_ID_W}, HB_DATA_W=${HB_DATA_W}"

#Credit: below wrapper template is generated by LLM 
cat > "$OUTPUT" << VERILOG_EOF
// Auto-generated Verilog wrapper for T1 + AXI Lite Wrapper
// Config-specific: AXI ID width = ${AXI_ID_W}, HB data width = ${HB_DATA_W}
// Do not edit, regenerated by gen_wrapper.sh

module t1_fpga_top (
    input  wire        aclk,
    input  wire        aresetn,

    // AXI4-Lite Slave (from PS GP0 - control plane)
    input  wire [6:0]  s_axi_ctrl_awaddr,
    input  wire [2:0]  s_axi_ctrl_awprot,
    input  wire        s_axi_ctrl_awvalid,
    output wire        s_axi_ctrl_awready,
    input  wire [31:0] s_axi_ctrl_wdata,
    input  wire [3:0]  s_axi_ctrl_wstrb,
    input  wire        s_axi_ctrl_wvalid,
    output wire        s_axi_ctrl_wready,
    output wire [1:0]  s_axi_ctrl_bresp,
    output wire        s_axi_ctrl_bvalid,
    input  wire        s_axi_ctrl_bready,
    input  wire [6:0]  s_axi_ctrl_araddr,
    input  wire [2:0]  s_axi_ctrl_arprot,
    input  wire        s_axi_ctrl_arvalid,
    output wire        s_axi_ctrl_arready,
    output wire [31:0] s_axi_ctrl_rdata,
    output wire [1:0]  s_axi_ctrl_rresp,
    output wire        s_axi_ctrl_rvalid,
    input  wire        s_axi_ctrl_rready,

    // AXI4 Master - highBandwidth (to PS HP0)
    output wire [${AXI_ID_W}-1:0]   m_axi_hb_awid,
    output wire [31:0]  m_axi_hb_awaddr,
    output wire [7:0]   m_axi_hb_awlen,
    output wire [2:0]   m_axi_hb_awsize,
    output wire [1:0]   m_axi_hb_awburst,
    output wire         m_axi_hb_awlock,
    output wire [3:0]   m_axi_hb_awcache,
    output wire [2:0]   m_axi_hb_awprot,
    output wire [3:0]   m_axi_hb_awqos,
    output wire         m_axi_hb_awvalid,
    input  wire         m_axi_hb_awready,
    output wire [${HB_DATA_W}-1:0]  m_axi_hb_wdata,
    output wire [${HB_STRB_W}-1:0]  m_axi_hb_wstrb,
    output wire         m_axi_hb_wlast,
    output wire         m_axi_hb_wvalid,
    input  wire         m_axi_hb_wready,
    input  wire [${AXI_ID_W}-1:0]   m_axi_hb_bid,
    input  wire [1:0]   m_axi_hb_bresp,
    input  wire         m_axi_hb_bvalid,
    output wire         m_axi_hb_bready,
    output wire [${AXI_ID_W}-1:0]   m_axi_hb_arid,
    output wire [31:0]  m_axi_hb_araddr,
    output wire [7:0]   m_axi_hb_arlen,
    output wire [2:0]   m_axi_hb_arsize,
    output wire [1:0]   m_axi_hb_arburst,
    output wire         m_axi_hb_arlock,
    output wire [3:0]   m_axi_hb_arcache,
    output wire [2:0]   m_axi_hb_arprot,
    output wire [3:0]   m_axi_hb_arqos,
    output wire         m_axi_hb_arvalid,
    input  wire         m_axi_hb_arready,
    input  wire [${AXI_ID_W}-1:0]   m_axi_hb_rid,
    input  wire [${HB_DATA_W}-1:0]  m_axi_hb_rdata,
    input  wire [1:0]   m_axi_hb_rresp,
    input  wire         m_axi_hb_rlast,
    input  wire         m_axi_hb_rvalid,
    output wire         m_axi_hb_rready,

    // AXI4 Master - indexed (to PS HP2)
    output wire [${AXI_ID_W}-1:0]   m_axi_idx_awid,
    output wire [31:0]  m_axi_idx_awaddr,
    output wire [7:0]   m_axi_idx_awlen,
    output wire [2:0]   m_axi_idx_awsize,
    output wire [1:0]   m_axi_idx_awburst,
    output wire         m_axi_idx_awlock,
    output wire [3:0]   m_axi_idx_awcache,
    output wire [2:0]   m_axi_idx_awprot,
    output wire [3:0]   m_axi_idx_awqos,
    output wire         m_axi_idx_awvalid,
    input  wire         m_axi_idx_awready,
    output wire [${IDX_DATA_W}-1:0] m_axi_idx_wdata,
    output wire [${IDX_STRB_W}-1:0] m_axi_idx_wstrb,
    output wire         m_axi_idx_wlast,
    output wire         m_axi_idx_wvalid,
    input  wire         m_axi_idx_wready,
    input  wire [${AXI_ID_W}-1:0]   m_axi_idx_bid,
    input  wire [1:0]   m_axi_idx_bresp,
    input  wire         m_axi_idx_bvalid,
    output wire         m_axi_idx_bready,
    output wire [${AXI_ID_W}-1:0]   m_axi_idx_arid,
    output wire [31:0]  m_axi_idx_araddr,
    output wire [7:0]   m_axi_idx_arlen,
    output wire [2:0]   m_axi_idx_arsize,
    output wire [1:0]   m_axi_idx_arburst,
    output wire         m_axi_idx_arlock,
    output wire [3:0]   m_axi_idx_arcache,
    output wire [2:0]   m_axi_idx_arprot,
    output wire [3:0]   m_axi_idx_arqos,
    output wire         m_axi_idx_arvalid,
    input  wire         m_axi_idx_arready,
    input  wire [${AXI_ID_W}-1:0]   m_axi_idx_rid,
    input  wire [${IDX_DATA_W}-1:0] m_axi_idx_rdata,
    input  wire [1:0]   m_axi_idx_rresp,
    input  wire         m_axi_idx_rlast,
    input  wire         m_axi_idx_rvalid,
    output wire         m_axi_idx_rready,

    // Interrupt
    output wire        irq
);

    // Internal wires: issue/retire between wrapper and T1
    wire        issue_valid;
    wire        issue_ready;
    wire [31:0] issue_bits_instruction;
    wire [31:0] issue_bits_rs1Data;
    wire [31:0] issue_bits_rs2Data;
    wire [31:0] issue_bits_vtype;
    wire [31:0] issue_bits_vl;
    wire [31:0] issue_bits_vstart;
    wire [31:0] issue_bits_vcsr;

    wire        retire_rd_valid;
    wire [4:0]  retire_rd_bits_rdAddress;
    wire [31:0] retire_rd_bits_rdData;
    wire        retire_rd_bits_isFp;
    wire        retire_csr_valid;
    wire [31:0] retire_csr_bits_vxsat;
    wire [31:0] retire_csr_bits_fflag;
    wire        retire_mem_valid;

    // Reset: T1 uses active-high, wrapper uses active-low
    wire t1_reset;
    assign t1_reset = ~aresetn;

    // =========================================================================
    // AXI Lite Wrapper
    // =========================================================================
    t1_axi_lite_wrapper u_axi_lite_wrapper (
        .aclk                       (aclk),
        .aresetn                    (aresetn),
        // AXI Lite slave
        .s_axi_awaddr               (s_axi_ctrl_awaddr),
        .s_axi_awprot               (s_axi_ctrl_awprot),
        .s_axi_awvalid              (s_axi_ctrl_awvalid),
        .s_axi_awready              (s_axi_ctrl_awready),
        .s_axi_wdata                (s_axi_ctrl_wdata),
        .s_axi_wstrb                (s_axi_ctrl_wstrb),
        .s_axi_wvalid               (s_axi_ctrl_wvalid),
        .s_axi_wready               (s_axi_ctrl_wready),
        .s_axi_bresp                (s_axi_ctrl_bresp),
        .s_axi_bvalid               (s_axi_ctrl_bvalid),
        .s_axi_bready               (s_axi_ctrl_bready),
        .s_axi_araddr               (s_axi_ctrl_araddr),
        .s_axi_arprot               (s_axi_ctrl_arprot),
        .s_axi_arvalid              (s_axi_ctrl_arvalid),
        .s_axi_arready              (s_axi_ctrl_arready),
        .s_axi_rdata                (s_axi_ctrl_rdata),
        .s_axi_rresp                (s_axi_ctrl_rresp),
        .s_axi_rvalid               (s_axi_ctrl_rvalid),
        .s_axi_rready               (s_axi_ctrl_rready),
        // Issue
        .issue_valid                (issue_valid),
        .issue_ready                (issue_ready),
        .issue_bits_instruction     (issue_bits_instruction),
        .issue_bits_rs1Data         (issue_bits_rs1Data),
        .issue_bits_rs2Data         (issue_bits_rs2Data),
        .issue_bits_vtype           (issue_bits_vtype),
        .issue_bits_vl              (issue_bits_vl),
        .issue_bits_vstart          (issue_bits_vstart),
        .issue_bits_vcsr            (issue_bits_vcsr),
        // Retire
        .retire_rd_valid            (retire_rd_valid),
        .retire_rd_bits_rdAddress   (retire_rd_bits_rdAddress),
        .retire_rd_bits_rdData      (retire_rd_bits_rdData),
        .retire_rd_bits_isFp        (retire_rd_bits_isFp),
        .retire_csr_valid           (retire_csr_valid),
        .retire_csr_bits_vxsat      (retire_csr_bits_vxsat),
        .retire_csr_bits_fflag      (retire_csr_bits_fflag),
        .retire_mem_valid           (retire_mem_valid),
        // IRQ
        .irq                        (irq)
    );

    // =========================================================================
    // T1 Vector Processor
    // =========================================================================
    T1 u_t1 (
        .clock                      (aclk),
        .reset                      (t1_reset),
        // Issue
        .issue_valid                (issue_valid),
        .issue_ready                (issue_ready),
        .issue_bits_instruction     (issue_bits_instruction),
        .issue_bits_rs1Data         (issue_bits_rs1Data),
        .issue_bits_rs2Data         (issue_bits_rs2Data),
        .issue_bits_vtype           (issue_bits_vtype),
        .issue_bits_vl              (issue_bits_vl),
        .issue_bits_vstart          (issue_bits_vstart),
        .issue_bits_vcsr            (issue_bits_vcsr),
        // Retire
        .retire_rd_valid            (retire_rd_valid),
        .retire_rd_bits_rdAddress   (retire_rd_bits_rdAddress),
        .retire_rd_bits_rdData      (retire_rd_bits_rdData),
        .retire_rd_bits_isFp        (retire_rd_bits_isFp),
        .retire_csr_valid           (retire_csr_valid),
        .retire_csr_bits_vxsat      (retire_csr_bits_vxsat),
        .retire_csr_bits_fflag      (retire_csr_bits_fflag),
        .retire_mem_valid           (retire_mem_valid),
        // highBandwidth AXI master
        .highBandwidthLoadStorePort_aw_valid    (m_axi_hb_awvalid),
        .highBandwidthLoadStorePort_aw_ready    (m_axi_hb_awready),
        .highBandwidthLoadStorePort_aw_bits_id  (m_axi_hb_awid),
        .highBandwidthLoadStorePort_aw_bits_addr(m_axi_hb_awaddr),
        .highBandwidthLoadStorePort_aw_bits_len (m_axi_hb_awlen),
        .highBandwidthLoadStorePort_aw_bits_size(m_axi_hb_awsize),
        .highBandwidthLoadStorePort_aw_bits_burst(m_axi_hb_awburst),
        .highBandwidthLoadStorePort_aw_bits_lock(m_axi_hb_awlock),
        .highBandwidthLoadStorePort_aw_bits_cache(m_axi_hb_awcache),
        .highBandwidthLoadStorePort_aw_bits_prot(m_axi_hb_awprot),
        .highBandwidthLoadStorePort_aw_bits_qos (m_axi_hb_awqos),
        .highBandwidthLoadStorePort_aw_bits_region(),
        .highBandwidthLoadStorePort_w_valid     (m_axi_hb_wvalid),
        .highBandwidthLoadStorePort_w_ready     (m_axi_hb_wready),
        .highBandwidthLoadStorePort_w_bits_data (m_axi_hb_wdata),
        .highBandwidthLoadStorePort_w_bits_strb (m_axi_hb_wstrb),
        .highBandwidthLoadStorePort_w_bits_last (m_axi_hb_wlast),
        .highBandwidthLoadStorePort_b_valid     (m_axi_hb_bvalid),
        .highBandwidthLoadStorePort_b_ready     (m_axi_hb_bready),
        .highBandwidthLoadStorePort_b_bits_id   (m_axi_hb_bid),
        .highBandwidthLoadStorePort_b_bits_resp (m_axi_hb_bresp),
        .highBandwidthLoadStorePort_ar_valid    (m_axi_hb_arvalid),
        .highBandwidthLoadStorePort_ar_ready    (m_axi_hb_arready),
        .highBandwidthLoadStorePort_ar_bits_id  (m_axi_hb_arid),
        .highBandwidthLoadStorePort_ar_bits_addr(m_axi_hb_araddr),
        .highBandwidthLoadStorePort_ar_bits_len (m_axi_hb_arlen),
        .highBandwidthLoadStorePort_ar_bits_size(m_axi_hb_arsize),
        .highBandwidthLoadStorePort_ar_bits_burst(m_axi_hb_arburst),
        .highBandwidthLoadStorePort_ar_bits_lock(m_axi_hb_arlock),
        .highBandwidthLoadStorePort_ar_bits_cache(m_axi_hb_arcache),
        .highBandwidthLoadStorePort_ar_bits_prot(m_axi_hb_arprot),
        .highBandwidthLoadStorePort_ar_bits_qos (m_axi_hb_arqos),
        .highBandwidthLoadStorePort_ar_bits_region(),
        .highBandwidthLoadStorePort_r_valid     (m_axi_hb_rvalid),
        .highBandwidthLoadStorePort_r_ready     (m_axi_hb_rready),
        .highBandwidthLoadStorePort_r_bits_id   (m_axi_hb_rid),
        .highBandwidthLoadStorePort_r_bits_data (m_axi_hb_rdata),
        .highBandwidthLoadStorePort_r_bits_resp (m_axi_hb_rresp),
        .highBandwidthLoadStorePort_r_bits_last (m_axi_hb_rlast),
        // indexed AXI master
        .indexedLoadStorePort_aw_valid          (m_axi_idx_awvalid),
        .indexedLoadStorePort_aw_ready          (m_axi_idx_awready),
        .indexedLoadStorePort_aw_bits_id        (m_axi_idx_awid),
        .indexedLoadStorePort_aw_bits_addr      (m_axi_idx_awaddr),
        .indexedLoadStorePort_aw_bits_len       (m_axi_idx_awlen),
        .indexedLoadStorePort_aw_bits_size      (m_axi_idx_awsize),
        .indexedLoadStorePort_aw_bits_burst     (m_axi_idx_awburst),
        .indexedLoadStorePort_aw_bits_lock      (m_axi_idx_awlock),
        .indexedLoadStorePort_aw_bits_cache     (m_axi_idx_awcache),
        .indexedLoadStorePort_aw_bits_prot      (m_axi_idx_awprot),
        .indexedLoadStorePort_aw_bits_qos       (m_axi_idx_awqos),
        .indexedLoadStorePort_aw_bits_region    (),
        .indexedLoadStorePort_w_valid           (m_axi_idx_wvalid),
        .indexedLoadStorePort_w_ready           (m_axi_idx_wready),
        .indexedLoadStorePort_w_bits_data       (m_axi_idx_wdata),
        .indexedLoadStorePort_w_bits_strb       (m_axi_idx_wstrb),
        .indexedLoadStorePort_w_bits_last       (m_axi_idx_wlast),
        .indexedLoadStorePort_b_valid           (m_axi_idx_bvalid),
        .indexedLoadStorePort_b_ready           (m_axi_idx_bready),
        .indexedLoadStorePort_b_bits_id         (m_axi_idx_bid),
        .indexedLoadStorePort_b_bits_resp       (m_axi_idx_bresp),
        .indexedLoadStorePort_ar_valid          (m_axi_idx_arvalid),
        .indexedLoadStorePort_ar_ready          (m_axi_idx_arready),
        .indexedLoadStorePort_ar_bits_id        (m_axi_idx_arid),
        .indexedLoadStorePort_ar_bits_addr      (m_axi_idx_araddr),
        .indexedLoadStorePort_ar_bits_len       (m_axi_idx_arlen),
        .indexedLoadStorePort_ar_bits_size      (m_axi_idx_arsize),
        .indexedLoadStorePort_ar_bits_burst     (m_axi_idx_arburst),
        .indexedLoadStorePort_ar_bits_lock      (m_axi_idx_arlock),
        .indexedLoadStorePort_ar_bits_cache     (m_axi_idx_arcache),
        .indexedLoadStorePort_ar_bits_prot      (m_axi_idx_arprot),
        .indexedLoadStorePort_ar_bits_qos       (m_axi_idx_arqos),
        .indexedLoadStorePort_ar_bits_region    (),
        .indexedLoadStorePort_r_valid           (m_axi_idx_rvalid),
        .indexedLoadStorePort_r_ready           (m_axi_idx_rready),
        .indexedLoadStorePort_r_bits_id         (m_axi_idx_rid),
        .indexedLoadStorePort_r_bits_data       (m_axi_idx_rdata),
        .indexedLoadStorePort_r_bits_resp       (m_axi_idx_rresp),
        .indexedLoadStorePort_r_bits_last       (m_axi_idx_rlast)
    );

endmodule
VERILOG_EOF

echo "Generated: ${OUTPUT}"
