# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  arithmetic = {
    pname = "arithmetic";
    version = "64b567c2ca6c65ef4455361d548beecf514b0d5a";
    src = fetchFromGitHub {
      owner = "Avimitin";
      repo = "arithmetic";
      rev = "64b567c2ca6c65ef4455361d548beecf514b0d5a";
      fetchSubmodules = false;
      sha256 = "sha256-ChvuuT0/D08EsmBrm+rSaU6YdUgZF/Emg7XCvFH0Ahg=";
    };
    date = "2026-02-05";
  };
  chisel = {
    pname = "chisel";
    version = "87b7f5d4b72c4a901fca597aa1b9f8731202efd9";
    src = fetchFromGitHub {
      owner = "chipsalliance";
      repo = "chisel";
      rev = "87b7f5d4b72c4a901fca597aa1b9f8731202efd9";
      fetchSubmodules = false;
      sha256 = "sha256-j7184gRjuFyW8W4rLnbcyob513Xc76h23BwcGZsxcbY=";
    };
    date = "2026-02-03";
  };
  chisel-interface = {
    pname = "chisel-interface";
    version = "2571ece011f2bdd4e5725bc712f3bdc8aba9a02a";
    src = fetchFromGitHub {
      owner = "chipsalliance";
      repo = "chisel-interface";
      rev = "2571ece011f2bdd4e5725bc712f3bdc8aba9a02a";
      fetchSubmodules = false;
      sha256 = "sha256-3GXqcrwTgu9Dm9dowXTOEXj2BW+p4Fntz45d4uqdwBE=";
    };
    date = "2026-02-05";
  };
  riscv-opcodes = {
    pname = "riscv-opcodes";
    version = "d0c4b0b4ef4c56fbd0499b010342b8107585233e";
    src = fetchFromGitHub {
      owner = "riscv";
      repo = "riscv-opcodes";
      rev = "d0c4b0b4ef4c56fbd0499b010342b8107585233e";
      fetchSubmodules = false;
      sha256 = "sha256-vJigg7GZDUWHmYTc4dsCon7JBs6IW1yY1GRPLfBqkMc=";
    };
    date = "2025-03-19";
  };
  rvdecoderdb = {
    pname = "rvdecoderdb";
    version = "22bd421d3817828a9ed2d45e61a039c9e4ccbfd2";
    src = fetchFromGitHub {
      owner = "sequencer";
      repo = "rvdecoderdb";
      rev = "22bd421d3817828a9ed2d45e61a039c9e4ccbfd2";
      fetchSubmodules = false;
      sha256 = "sha256-q0y9ugElJU+W3dubJ7ITo7/Q2bKz6Mz6cGKIQX9OBA8=";
    };
    date = "2025-05-14";
  };
  zaozi = {
    pname = "zaozi";
    version = "51ca7a70e9a89d2cb870c1e8351026ed849a5cc6";
    src = fetchFromGitHub {
      owner = "sequencer";
      repo = "zaozi";
      rev = "51ca7a70e9a89d2cb870c1e8351026ed849a5cc6";
      fetchSubmodules = false;
      sha256 = "sha256-KfiPI8boZf349qFnsyARdcpMUma4jWJm6K1nJZoz8Wk=";
    };
    date = "2025-07-11";
  };
}
